apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"dp-example"},"name":"dp-example","namespace":"default"},"spec":{"minReadySeconds":2,"paused":false,"progressDeadlineSeconds":600,"replicas":8,"revisionHistoryLimit":20,"selector":{"matchLabels":{"app":"dp-example"}},"strategy":{"rollingUpdate":{"maxSurge":2,"maxUnavailable":2}},"template":{"metadata":{"labels":{"app":"dp-example"}},"spec":{"containers":[{"image":"httpd:2.4","imagePullPolicy":"IfNotPresent","name":"httpd","ports":[{"containerPort":80}]}]}}}}
  creationTimestamp: "2022-06-17T15:23:59Z"
  generation: 1
  labels:
    app: dp-example
  name: dp-example
  namespace: default
  resourceVersion: "12045"
  uid: b705d20f-0c80-4a48-b467-ea61f819337d
spec:
  minReadySeconds: 2
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 20
  selector:
    matchLabels:
      app: dp-example
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 2
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dp-example
    spec:
      containers:
      - image: httpd:2.4
        imagePullPolicy: IfNotPresent
        name: httpd
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 8
  conditions:
  - lastTransitionTime: "2022-06-17T15:23:59Z"
    lastUpdateTime: "2022-06-17T15:25:53Z"
    message: ReplicaSet "dp-example-7cdd745ddd" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2022-06-29T13:06:24Z"
    lastUpdateTime: "2022-06-29T13:06:24Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 8
  replicas: 8
  updatedReplicas: 8
