apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-06-17T15:31:21Z"
  labels:
    app: dp-example
  name: svc-example
  namespace: default
  resourceVersion: "10608"
  uid: 98099940-7ec2-4701-84c2-9c9be7c3ebed
spec:
  clusterIP: 10.9.33.77
  clusterIPs:
  - 10.9.33.77
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32445
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: dp-example
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
